[GRYPHGEAR_SSH_CLIENT]
type = client
address = 127.0.0.1
port = 9995
destination = gw6v4m6asvaft4sbr6aftlk3br2asq7ubxgxvnc4twsh5eq6l5aq.b32.i2p
inbound.length = 0
outbound.length = 0
destinationport = 22
keys = keys/testclient-keys.dat
